import { V4_MOTION } from './productionMotion'

export const PRINTER_TIMING = {
  press: V4_MOTION.commitResponse,
  buttonDepression: V4_MOTION.buttonDepression,
  dockCompression: V4_MOTION.dockCompression,
  chamberSettle: V4_MOTION.chamberSettle,
  preScanBreath: V4_MOTION.preScanBreath,
  scannerSweep: V4_MOTION.scannerSweep,
  postScanBreath: V4_MOTION.postScanBreath,
  printerWake: V4_MOTION.printerWake,
  blankPaperHold: V4_MOTION.blankPaperHold,
  blankLeaderReveal: V4_MOTION.blankLeaderReveal,
  feedDuration: V4_MOTION.receiptFeed,
  cvsPrimaryFeedDuration: V4_MOTION.cvsPrimaryReceiptFeed,
  verdictSilence: V4_MOTION.verdictSilence,
  stampDuration: V4_MOTION.verdictImpact,
  evidenceSettlement: V4_MOTION.evidenceSettlement,
  cvsCompletionSettle: V4_MOTION.cvsCompletionSettle,
  cvsApparentCompletion: V4_MOTION.cvsApparentCompletion,
  falseCompletePause: V4_MOTION.cvsFalseEndingSilence,
  cvsAdditionalRewardsReveal: V4_MOTION.cvsAdditionalRewardsReveal,
  cvsMessageReadingHold: V4_MOTION.cvsMessageReadingHold,
  cvsPrinterRestart: V4_MOTION.cvsPrinterRestart,
  couponFeedDuration: V4_MOTION.cvsCouponFeed,
  cvsTrueCompleteHold: V4_MOTION.cvsTrueCompleteHold,
} as const
