import type { ReceiptTheme } from '../themes'
import type { ExportFormat } from '../v2'
import type { FieldAccessContext } from './fieldAccessTypes'

export function applyFieldAccessProvenance(
  source: HTMLCanvasElement,
  format: ExportFormat,
  theme: ReceiptTheme,
  context: FieldAccessContext | null,
): HTMLCanvasElement {
  if (!context) return source
  if (format === 'full') return appendReceiptProvenance(source, theme, context)

  const canvas = document.createElement('canvas')
  canvas.width = source.width
  canvas.height = source.height
  const ctx = canvas.getContext('2d')
  if (!ctx) return source

  ctx.drawImage(source, 0, 0)
  const stripHeight = 78
  ctx.fillStyle = theme.palette.ink
  ctx.fillRect(0, canvas.height - stripHeight, canvas.width, stripHeight)
  ctx.fillStyle = theme.palette.paper
  ctx.textAlign = 'center'
  ctx.textBaseline = 'middle'
  ctx.font = '700 13px ui-monospace, SFMono-Regular, Menlo, monospace'
  ctx.fillText(
    `FIELD ACCESS / LD–${context.edition}   ARTIFACT SERIAL / ${context.token}`,
    canvas.width / 2,
    canvas.height - 48,
  )
  ctx.font = '11px ui-monospace, SFMono-Regular, Menlo, monospace'
  ctx.fillText(
    'GENERATED BY LAB DOJO · @LABDOJO',
    canvas.width / 2,
    canvas.height - 25,
  )

  return canvas
}

function appendReceiptProvenance(
  source: HTMLCanvasElement,
  theme: ReceiptTheme,
  context: FieldAccessContext,
): HTMLCanvasElement {
  const footerHeight = 92
  const canvas = document.createElement('canvas')
  canvas.width = source.width
  canvas.height = source.height + footerHeight
  const ctx = canvas.getContext('2d')
  if (!ctx) return source

  ctx.fillStyle = theme.palette.paper
  ctx.fillRect(0, 0, canvas.width, canvas.height)
  ctx.drawImage(source, 0, 0)
  ctx.strokeStyle = theme.palette.ink
  ctx.lineWidth = Math.max(1, Math.round(canvas.width / 420))
  ctx.beginPath()
  ctx.moveTo(24, source.height + 1)
  ctx.lineTo(canvas.width - 24, source.height + 1)
  ctx.stroke()

  ctx.fillStyle = theme.palette.ink
  ctx.textAlign = 'left'
  ctx.textBaseline = 'middle'
  ctx.font = '700 12px ui-monospace, SFMono-Regular, Menlo, monospace'
  ctx.fillText(`FIELD ACCESS / LD–${context.edition}`, 28, source.height + 31)
  ctx.textAlign = 'right'
  ctx.fillText(`ARTIFACT SERIAL / ${context.token}`, canvas.width - 28, source.height + 31)
  ctx.textAlign = 'center'
  ctx.font = '10px ui-monospace, SFMono-Regular, Menlo, monospace'
  ctx.fillText('GENERATED BY LAB DOJO · @LABDOJO', canvas.width / 2, source.height + 65)

  return canvas
}
